language: node_js
node_js:
  - "12"
branches:
  only:
    - master
before_deploy:
  - npm run build -- --public-url ./ludum-46
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: ./dist
  target_branch: gh-pages
  on:
    branch: master
