language: node_js
node_js:
  - "12"
branches:
  only:
    - master
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: ./dist
  target_branch: gh_pages
  on:
    branch: master
